src/AppBundle/Entity/Person.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
/**
 * Person
 *
 * @ORM\Table(name="stabam_person")
 * @ORM\Entity
 */
class Person
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\OneToMany(targetEntity="Person", mappedBy="mutter")
     * @ORM\OneToMany(targetEntity="Person", mappedBy="vater")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="vorname", type="string", length=255)
     */
    private $vorname;

    /**
     * @var string
     *
     * @ORM\Column(name="vorname2", type="string", length=255, nullable=true)
     */
    private $vorname2;

    /**
     * @var string
     *
     * @ORM\Column(name="vorname3", type="string", length=255, nullable=true)
     */
    private $vorname3;

    /**
     * @var string
     *
     * @ORM\Column(name="nachname", type="string", length=255)
     */
    private $nachname;

    /**
     * @var string
     *
     * @ORM\Column(name="nachname_geboren", type="string", length=255, nullable=true)
     */
    private $nachnameGeboren;

    /**
     * @param string $nachnameGeboren
     */
    public function setNachnameGeboren($nachnameGeboren)
    {
        $this->nachnameGeboren = $nachnameGeboren;
    }

    /**
     * @var string
     *
     * @ORM\Column(name="geschlecht", type="string", length=1)
     */
    private $geschlecht;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="geboren_am", type="datetime")
     */
    private $geborenAm;

    /**
     * @var string
     *
     * @ORM\Column(name="geburtsort", type="string", length=255)
     */
    private $geburtsort;

    /**
     * @var string
     *
     * @ORM\Column(name="beruf", type="string", length=255)
     */
    private $beruf;

    /**
     * @var string
     *
     * @ORM\Column(name="besonderes", type="text", nullable=true)
     */
    private $besonderes;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="gestorben_am", type="datetime", nullable=true)
     */
    private $gestorbenAm;

    /**
     * @var string
     *
     * @ORM\Column(name="sterbeort", type="string", length=255, nullable=true)
     */
    private $sterbeort;

    /**
     * @var integer)
     *
     * @ORM\ManyToOne(targetEntity="Person")
     * @ORM\JoinColumn(name="mutter", referencedColumnName="id", nullable=true)
     */
    private $mutter;

    /**
     * @var integer)
     *
     * @ORM\ManyToOne(targetEntity="Person")
     * @ORM\JoinColumn(name="vater", referencedColumnName="id", nullable=true)
     */
    private $vater;


    /**
     * @ORM\ManyToMany(targetEntity="Faktum")
     * @ORM\JoinTable(name="stabam_person_faktums",
     *      joinColumns={@ORM\JoinColumn(name="person_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="faktum_id", referencedColumnName="id", unique=true)}
     *      )
     */
    private $faktums;




    public function __construct()
    {
        $this->faktums = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getVater()
    {
        return $this->vater;
    }

    /**
     * @param int $vater
     */
    public function setVater($vater)
    {
        $this->vater = $vater;
    }


    /**
     * @return int
     */
    public function getMutter()
    {
        return $this->mutter;
    }

    /**
     * @param int $mutter
     */
    public function setMutter($mutter)
    {
        $this->mutter = $mutter;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set vorname
     *
     * @param string $vorname
     *
     * @return Person
     */
    public function setVorname($vorname)
    {
        $this->vorname = $vorname;

        return $this;
    }

    /**
     * Get vorname
     *
     * @return string
     */
    public function getVorname()
    {
        return $this->vorname;
    }

    /**
     * Set vorname2
     *
     * @param string $vorname2
     *
     * @return Person
     */
    public function setVorname2($vorname2)
    {
        $this->vorname2 = $vorname2;

        return $this;
    }

    /**
     * Get vorname2
     *
     * @return string
     */
    public function getVorname2()
    {
        return $this->vorname2;
    }

    /**
     * Set vorname3
     *
     * @param string $vorname3
     *
     * @return Person
     */
    public function setVorname3($vorname3)
    {
        $this->vorname3 = $vorname3;

        return $this;
    }

    /**
     * Get vorname3
     *
     * @return string
     */
    public function getVorname3()
    {
        return $this->vorname3;
    }

    /**
     * Set nachname
     *
     * @param string $nachname
     *
     * @return Person
     */
    public function setNachname($nachname)
    {
        $this->nachname = $nachname;

        return $this;
    }

    /**
     * Get nachname
     *
     * @return string
     */
    public function getNachname()
    {
        return $this->nachname;
    }

    /**
     * Get nachnameGeboren
     *
     * @return string
     */
    public function getNachnameGeboren()
    {
        return $this->nachnameGeboren;
    }

    /**
     * Set geschlecht
     *
     * @param string $geschlecht
     *
     * @return Person
     */
    public function setGeschlecht($geschlecht)
    {
        $this->geschlecht = $geschlecht;

        return $this;
    }

    /**
     * Get geschlecht
     *
     * @return string
     */
    public function getGeschlecht()
    {
        return $this->geschlecht;
    }

    /**
     * Set geborenAm
     *
     * @param \DateTime $geborenAm
     *
     * @return Person
     */
    public function setGeborenAm($geborenAm)
    {
        $this->geborenAm = $geborenAm;

        return $this;
    }

    /**
     * Get geborenAm
     *
     * @return \DateTime
     */
    public function getGeborenAm()
    {
        return $this->geborenAm;
    }

    /**
     * Set geburtsort
     *
     * @param string $geburtsort
     *
     * @return Person
     */
    public function setGeburtsort($geburtsort)
    {
        $this->geburtsort = $geburtsort;

        return $this;
    }

    /**
     * Get geburtsort
     *
     * @return string
     */
    public function getGeburtsort()
    {
        return $this->geburtsort;
    }

    /**
     * Set beruf
     *
     * @param string $beruf
     *
     * @return Person
     */
    public function setBeruf($beruf)
    {
        $this->beruf = $beruf;

        return $this;
    }

    /**
     * Get beruf
     *
     * @return string
     */
    public function getBeruf()
    {
        return $this->beruf;
    }

    /**
     * Set besonderes
     *
     * @param string $besonderes
     *
     * @return Person
     */
    public function setBesonderes($besonderes)
    {
        $this->besonderes = $besonderes;

        return $this;
    }

    /**
     * Get besonderes
     *
     * @return string
     */
    public function getBesonderes()
    {
        return $this->besonderes;
    }

    /**
     * Set gestorbenAm
     *
     * @param \DateTime $gestorbenAm
     *
     * @return Person
     */
    public function setGestorbenAm($gestorbenAm)
    {
        $this->gestorbenAm = $gestorbenAm;

        return $this;
    }

    /**
     * Get gestorbenAm
     *
     * @return \DateTime
     */
    public function getGestorbenAm()
    {
        return $this->gestorbenAm;
    }

    /**
     * Set sterbeort
     *
     * @param string $sterbeort
     *
     * @return Person
     */
    public function setSterbeort($sterbeort)
    {
        $this->sterbeort = $sterbeort;

        return $this;
    }

    /**
     * Get sterbeort
     *
     * @return string
     */
    public function getSterbeort()
    {
        return $this->sterbeort;
    }

    /**
     * @return mixed
     */
    public function getFaktums()
    {
        return $this->faktums;
    }

    /**
     * @param mixed $faktums
     */
    public function setFaktums($faktums)
    {
        $this->faktums = $faktums;
    }



    /**
     * Display full name
     * @return string
     */
    public function getFullname(){
        return $this->getVorname() .
        ($this->getVorname2() ? " ".$this->getVorname2() : "").
        ($this->getVorname3() ? " ".$this->getVorname3() : "").
            " ".$this->getNachname();
    }
}

src/AppBundle/Controller/PersonsController.php
<?php

namespace AppBundle\Controller;

use AppBundle\AppBundle;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\FormError;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use AppBundle\Entity\Person;
use AppBundle\Form\PersonType;

/**
 * Person controller.
 *
 * @Route("/persons")
 */
class PersonsController extends Controller
{

    /**
     * Lists all Person entities.
     *
     * @Route("/list", name="person")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $entities = $this->get('stabam.person.handler')->getPersons();

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new Person entity.
     * @Route("/create", name="person_create")
     * @Method("POST")
     * @Template("AppBundle:Person:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $formHandler = $this->container->get('stabam.person.form.handler');
        $personHandler = $this->container->get('stabam.person.handler');

        return $formHandler->buildForm($request, $personHandler->newPerson(), 'person');
    }

    /**
     * Creates a form to create a Person entity.
     *
     * @param Person $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Person $entity)
    {
        $form = $this->createForm(PersonType::class, $entity, array(
            'action' => $this->generateUrl('person_create'),
            'method' => 'POST'
        ));

        return $form;
    }

    /**
     * Displays a form to create a new Person entity.
     *
     * @Route("/new", name="person_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = $this->get('stabam.person.handler')->newPerson();

        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Person entity.
     *
     * @Route("/{id}", name="person_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Person')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Person entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Person entity.
     *
     * @Route("/{id}/edit", name="person_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Person')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Person entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Person entity.
    *
    * @param Person $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Person $entity)
    {
        $form = $this->createForm(new PersonType(), $entity, array(
            'action' => $this->generateUrl('person_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        return $form;
    }
    /**
     * Edits an existing Person entity.
     *
     * @Route("/{id}", name="person_update")
     * @Method("PUT")
     * @Template("AppBundle:Person:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Person')->find($id);
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Person entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('person_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Person entity.
     *
     * @Route("/{id}", name="person_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('AppBundle:Person')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Person entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('person'));
    }

    /**
     * Creates a form to delete a Person entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('person_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', SubmitType::class, array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

src/AppBundle/Controller/api/PersonController.php
<?php

namespace AppBundle\Controller\api;

use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\View\View;
use Symfony\Component\HttpFoundation\Request;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;

class PersonController extends FOSRestController
{
    /** @ApiDoc(
     *     statusCodes={
     *         200="Returned when successful",
     *         403="Returned when the user is not authorized to say hello",
     *         404={
     *           "Returned when the user is not found",
     *           "Returned when something else is not found"
     *         }
     *     }
     * )
     */
    public function getPersonAction ($id)
    {
        $person = $this->container
            ->get('stabam.person.handler')
            ->getPerson($id);

        $view = View::create()
            ->setData(array('data' => $person));

        return $this->handleView($view);

    }

    public function getPersonsAction(){
        $persons = $this->container
            ->get('stabam.person.handler')
            ->getPersons();

        $view = View::create()
            ->setData(array('data' => $persons));

        return $this->handleView($view);
    }

    public function postPersonAction(Request $request){


        //return new View(, Response::HTTP_CREATED);
    }

    public function deletePersonAction(Request $request, $id){

    }
}

src/AppBundle/Resources/views/Persons/getPersons.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h2 class="section-header">Personenübersicht</h2>
    <div class="tile row col s12">
        <div class="tile-content">
            <div class="input-field col s4">
                <input placeholder="Suche" id="search" type="text">
            </div>
            <table class="responsive-table highlight">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Nachname (geb.)</th>
                    <th>Geschlecht</th>
                    <th>Mutter</th>
                    <th>Vater</th>
                    <th>Geboren am (Ort)</th>
                    <th>Gestorben am (Ort)</th>
                    <th>Beruf</th>
                    <th>Besonderes</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for entity in entities %}
                    <tr>
                        <td><a href="{{ path('person_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                        <td>{{ entity.fullname }}</td>
                        <td>{{ entity.nachname }} ({{ entity.nachnameGeboren }})</td>
                        <td>{{ entity.geschlecht }}</td>

                        {% if entity.mutter is not null %}
                            <td><a href="{{ path('person_show', {'id' : entity.mutter.id}) }}">{{ entity.mutter.fullname }}</a></td>
                        {% else %}
                            <td>null</td>
                        {% endif %}

                        {% if entity.vater is not null %}
                            <td><a href="{{ path('person_show', {'id' : entity.vater.id}) }}">{{ entity.vater.fullname }}</a></td>
                        {% else %}
                            <td>null</td>
                        {% endif %}

                        <td>{{ entity.geborenAm|date('d.m.Y') }} ({{ entity.geburtsort }})</td>
                        <td>{% if entity.gestorbenAm %}{{ entity.gestorbenAm|date('d.m.Y') }} ({{ entity.sterbeort }}){% endif %}</td>
                        <td>{{ entity.beruf }}</td>
                        <td>{{ entity.besonderes }}</td>
                        <td><a class='dropdown-button' href='#' data-activates='dropdown1'><i class="material-icons">more_vert</i></a></td>
                        <!-- Dropdown Trigger -->


                        <!-- Dropdown Structure -->
                        <ul id='dropdown1' class='dropdown-content'>
                            <li>
                                <a href="{{ path('person_show', { 'id': entity.id }) }}"><i class="material-icons">search</i> Show</a>
                            </li>
                            <li>
                                <a href="{{ path('person_edit', { 'id': entity.id }) }}"><i class="material-icons">mode_edit</i> Edit</a>
                            </li>
                            <li>
                                <a href="{{ path('person_delete', { 'id': entity.id }) }}"><i class="material-icons">close</i> Delete</a>
                            </li>
                        </ul>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                <a class="btn-floating btn-large" href="">
                    <i class="large material-icons">add</i>
                </a>
            </div>
            <div class="row col s12">
                <div class="col s4">Zeige xx Einträge an.</div>
                <div class="col s8">
                    <ul class="pagination center ">
                        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
                        <li class="active"><a href="#!">1</a></li>
                        <li class="waves-effect"><a href="#!">2</a></li>
                        <li class="waves-effect"><a href="#!">3</a></li>
                        <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
                    </ul>
                </div>

            </div>
        </div>

    </div>

{% endblock %}

src/AppBundle/Resources/views/Persons/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h2 class="section-header">Personenübersicht</h2>
    <div class="tile row col s12">
        <div class="tile-content">
            <div class="input-field col s4">
                <input placeholder="Suche" id="search" type="text">
            </div>
            <table class="responsive-table highlight">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Nachname (geb.)</th>
                    <th>Geschlecht</th>
                    <th>Mutter</th>
                    <th>Vater</th>
                    <th>Geboren am (Ort)</th>
                    <th>Gestorben am (Ort)</th>
                    <th>Beruf</th>
                    <th>Besonderes</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for entity in entities %}
                    <tr>
                        <td><a href="{{ path('person_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                        <td>{{ entity.fullname }}</td>
                        <td>{{ entity.nachname }} ({{ entity.nachnameGeboren }})</td>
                        <td>{{ entity.geschlecht }}</td>

                        {% if entity.mutter is not null %}
                            <td><a href="{{ path('person_show', {'id' : entity.mutter.id}) }}">{{ entity.mutter.fullname }}</a></td>
                        {% else %}
                            <td>null</td>
                        {% endif %}

                        {% if entity.vater is not null %}
                            <td><a href="{{ path('person_show', {'id' : entity.vater.id}) }}">{{ entity.vater.fullname }}</a></td>
                        {% else %}
                            <td>null</td>
                        {% endif %}

                        <td>{{ entity.geborenAm|date('d.m.Y') }} ({{ entity.geburtsort }})</td>
                        <td>{% if entity.gestorbenAm %}{{ entity.gestorbenAm|date('d.m.Y') }} ({{ entity.sterbeort }}){% endif %}</td>
                        <td>{{ entity.beruf }}</td>
                        <td>{{ entity.besonderes }}</td>
                        <td><a class='dropdown-button' href='#' data-activates='dropdown1'><i class="material-icons">more_vert</i></a></td>
                        <!-- Dropdown Trigger -->


                        <!-- Dropdown Structure -->
                        <ul id='dropdown1' class='dropdown-content'>
                            <li>
                                <a href="{{ path('person_show', { 'id': entity.id }) }}"><i class="material-icons">search</i> Show</a>
                            </li>
                            <li>
                                <a href="{{ path('person_edit', { 'id': entity.id }) }}"><i class="material-icons">mode_edit</i> Edit</a>
                            </li>
                            <li>
                                <a href="{{ path('person_delete', { 'id': entity.id }) }}"><i class="material-icons">close</i> Delete</a>
                            </li>
                        </ul>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                <a class="btn-floating btn-large" href="{{ path('person_new') }}">
                    <i class="large material-icons">add</i>
                </a>
            </div>
            <div class="row col s12">
                <div class="col s4">Zeige xx Einträge an.</div>
                <div class="col s8">
                    <ul class="pagination center ">
                        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
                        <li class="active"><a href="#!">1</a></li>
                        <li class="waves-effect"><a href="#!">2</a></li>
                        <li class="waves-effect"><a href="#!">3</a></li>
                        <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
                    </ul>
                </div>

            </div>
        </div>

    </div>

{% endblock %}

src/AppBundle/Resources/views/Persons/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}


    <div class="row col s12">
        <div class="col s5">
            <h2 class="section-header">{{ entity.fullname }}</h2>
            <div class="tile">
                <div class="tile-content">
                    <table class="record_properties">
                        <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ entity.id }}</td>
                        </tr>
                        <tr>
                            <th>Vorname</th>
                            <td>{{ entity.vorname }}</td>
                        </tr>
                        <tr>
                            <th>Vorname2</th>
                            <td>{{ entity.vorname2 }}</td>
                        </tr>
                        <tr>
                            <th>Vorname3</th>
                            <td>{{ entity.vorname3 }}</td>
                        </tr>
                        <tr>
                            <th>Nachname</th>
                            <td>{{ entity.nachname }}</td>
                        </tr>
                        <tr>
                            <th>Geschlecht</th>
                            <td>{{ entity.geschlecht }}</td>
                        </tr>
                        <tr>
                            <th>Geborenam</th>
                            <td>{{ entity.geborenAm|date('Y-m-d H:i:s') }}</td>
                        </tr>
                        <tr>
                            <th>Geburtsort</th>
                            <td>{{ entity.geburtsort }}</td>
                        </tr>
                        <tr>
                            <th>Beruf</th>
                            <td>{{ entity.beruf }}</td>
                        </tr>
                        <tr>
                            <th>Besonderes</th>
                            <td>{{ entity.besonderes }}</td>
                        </tr>
                        <tr>
                            <th>Gestorbenam</th>
                            <td>{{ entity.gestorbenAm|date('Y-m-d H:i:s') }}</td>
                        </tr>
                        <tr>
                            <th>Sterbeort</th>
                            <td>{{ entity.sterbeort }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s7">
            <h2 class="section-header">Ereignisse</h2>
            <div class="ui-timline-container">
                <section class="ui-timeline">

                    <!--                   <article class="tl-item">
                                           <div class="tl-body">
                                               <div class="tl-entry">
                                                   <div class="tl-caption">
                                                       <a href="javascript:;" class="btn btn-primary btn-block">Gestorben</a>
                                                   </div>
                                               </div>
                                           </div>
                                       </article>
                   -->

                    {% if entity.gestorbenAm %}
                    <article class="tl-item alt">
                        <div class="tl-body">
                            <div class="tl-entry">
                                <div class="tl-time">{{ entity.gestorbenAm|date('d.m.Y') }}</div>
                                <div class="tl-icon btn-icon-round btn-icon white-text black "><i class="fa fa-crisscross fa-2x"></i></div>
                                <div class="tl-content">
                                    <h4 class="tl-tile text-primary">Gestorben</h4>
                                </div>
                            </div>
                        </div>
                    </article>
                    {% endif %}

                    <article class="tl-item">
                        <div class="tl-body">
                            <div class="tl-entry">
                                <div class="tl-time">16.12.2015</div>
                                <div class="tl-icon btn-icon-round btn-icon white-text red "><i class="fa fa-heart"></i></div>
                                <div class="tl-content">
                                    <h4 class="tl-tile text-primary">Geheiratet</h4>
                                </div>
                            </div>
                        </div>
                    </article>

                    <article class="tl-item alt">
                        <div class="tl-body">
                            <div class="tl-entry">
                                <div class="tl-time">{{ entity.geborenAm|date('d.m.Y')  }}</div>
                                <div class="tl-icon green white-text"><i class="fa fa-asterisk"></i></div>
                                <div class="tl-content">
                                    <h4 class="tl-tile text-danger">Geboren in {{ entity.geburtsort }}</h4>
                                </div>
                            </div>
                        </div>
                    </article>

                </section>
            </div>

        </div>


    </div>
{% endblock %}